export default {
    SET_EMPLOYEES: "SET_EMPLOYEES",
    FETCH_EMPLOYEES: "FETCH_EMPLOYEES",
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    SET_ADDED_EMPLOYEE: "SET_ADDED_EMPLOYEE",
    REMOVE_EMPLOYEE: "REMOVE_EMPLOYEE",
    REMOVE_EMPLOYEE_DONE: "REMOVE_EMPLOYEE_DONE",
    UPDATE_SEARCHQ: "UPDATE_SEARCHQ",
    SET_LOADER: "SET_LOADER",
    SET_EMPLOYEE: "SET_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    UPDATE_EMPLOYEE_DONE: "UPDATE_EMPLOYEE_DONE"
}